#!/bin/bash
### BEGIN INIT INFO
## Load firewalls rules for balena
### END INIT INFO

case "$1" in 
  start) 
    nft flush table ip balena 
    nft -f /etc/nftables/balena.nft
    echo "load firewall ruleset for balena"
    ;;   

  stop)
    nft flush table ip balena 
    echo "flush firewall ruleset for balena"
    ;;

  *) echo "Usage:/etc/init.d/balenafw {start|stop}"
     exit 1
     ;;
esac

exit 0
